'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, Building2, CalendarDays, Clock3, Filter, MapPin, RotateCcw, Search, UsersRound } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import MobileTabBar from '@/components/MobileTabBar';
import CareerApplicationForm from './CareerApplicationForm';
import { careerService } from '@/services/careerService';
import type { CareerJob, CareerOptions } from '@/types/career';

const date = (value?: string | null) => value ? new Intl.DateTimeFormat('vi-VN').format(new Date(value)) : 'Không giới hạn';
const salary = (job: CareerJob) => job.salary_text || (job.salary_min || job.salary_max ? `${job.salary_min || ''}${job.salary_min && job.salary_max ? ' - ' : ''}${job.salary_max || ''} ${job.salary_currency}` : 'Thỏa thuận');

export default function CareerListClient({ initialOptions, initialJobs, initialMeta }: { initialOptions: CareerOptions; initialJobs: CareerJob[]; initialMeta: { total: number; last_page: number } }) {
  const [jobs, setJobs] = useState<CareerJob[]>(initialJobs || []); const [meta, setMeta] = useState(initialMeta || { total: initialJobs?.length || 0, last_page: 1 });
  const [loading, setLoading] = useState(false); const [page, setPage] = useState(1); const [applyOpen, setApplyOpen] = useState(false);
  const [filters, setFilters] = useState({ q: '', department: '', location: '', employment_type: '', sort: 'newest' });
  const [mobileFilters, setMobileFilters] = useState(false);
  useEffect(() => { if (page === 1 && Object.values(filters).every((value, index) => value === (index === 4 ? 'newest' : ''))) return; const timer = setTimeout(async () => { setLoading(true); try { const res = await careerService.jobs({ ...filters, page, per_page: 9 }); setJobs(res.data); setMeta({ total: res.meta?.total || 0, last_page: res.meta?.last_page || 1 }); } catch { /* Keep the last successful server response visible. */ } finally { setLoading(false); } }, 250); return () => clearTimeout(timer); }, [filters, page]);
  const content = initialOptions.page_content;
  const update = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const reset = () => { setFilters({ q: '', department: '', location: '', employment_type: '', sort: 'newest' }); setPage(1); };

  return <><Header /><MobileTabBar /><main className="bg-[#FBF8F2] pb-20 lg:pb-0">
    <section className="border-b border-[#E7D9C6] bg-[#F4EEE4]"><div className="mx-auto grid max-w-[1440px] gap-8 px-4 py-10 sm:px-8 lg:grid-cols-[1fr_45%] lg:px-12 lg:py-16">
      <div className="flex flex-col justify-center"><p className="text-sm text-[#8C7A6B]">Trang chủ / Tuyển dụng</p><p className="mt-8 text-xs font-bold uppercase tracking-widest text-[#B88746]">{content.eyebrow || 'Cơ hội nghề nghiệp'}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-tight text-[#1F1B16] sm:text-5xl">{content.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#665B51]">{content.description}</p><a href="#vi-tri-dang-tuyen" className="mt-7 inline-flex w-fit items-center gap-2 rounded-md bg-[#B88746] px-5 py-3 font-semibold text-white">Xem vị trí đang tuyển <ArrowRight className="size-4" /></a></div>
      <div className="min-h-64 overflow-hidden rounded-lg bg-[#DDD1BF]">{content.hero_image ? <img src={content.hero_image} alt="Cơ hội nghề nghiệp tại Masterise Homes" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-[#8C7A6B]"><BriefcaseBusiness className="size-16" /></div>}</div>
    </div><div className="mx-auto grid max-w-[1344px] grid-cols-3 border-x border-t border-[#E7D9C6] bg-white"><Stat icon={BriefcaseBusiness} value={initialOptions.stats.open_jobs} label="Vị trí đang mở" /><Stat icon={Building2} value={initialOptions.stats.departments} label="Phòng ban" /><Stat icon={MapPin} value={initialOptions.stats.locations} label="Địa điểm" /></div></section>

    {!!content.benefits?.length && <section className="mx-auto max-w-[1344px] px-4 py-12 sm:px-8"><p className="text-xs font-bold uppercase tracking-widest text-[#B88746]">Môi trường làm việc</p><h2 className="mt-2 text-3xl font-semibold">Vì sao nên gia nhập?</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{content.benefits.map((benefit, index) => <article key={index} className="rounded-md border border-[#E7D9C6] bg-white p-6"><div className="mb-4 grid size-10 place-items-center rounded-md bg-[#F4EEE4] text-[#B88746]"><UsersRound className="size-5" /></div><h3 className="text-lg font-semibold">{benefit.title}</h3><p className="mt-2 text-sm leading-6 text-[#6E6258]">{benefit.description}</p></article>)}</div></section>}

    <section id="vi-tri-dang-tuyen" className="border-y border-[#E7D9C6] bg-white"><div className="mx-auto max-w-[1344px] px-4 py-12 sm:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#B88746]">Vị trí đang tuyển</p><h2 className="mt-2 text-3xl font-semibold">Tìm cơ hội phù hợp với bạn</h2></div><button onClick={() => setMobileFilters(!mobileFilters)} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm md:hidden"><Filter className="size-4" /> Bộ lọc</button></div>
      <div className={`${mobileFilters ? 'grid' : 'hidden'} mt-6 gap-3 rounded-md border border-[#E7D9C6] bg-[#FBF8F2] p-4 md:grid md:grid-cols-[1.4fr_repeat(3,1fr)_auto]`}><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-[#8C7A6B]" /><input value={filters.q} onChange={(e) => update('q', e.target.value)} placeholder="Tìm vị trí, mã tin..." className="w-full rounded-md border border-[#DCCDB9] bg-white py-3 pl-10 pr-3 text-sm" /></label><Select value={filters.department} onChange={(v) => update('department', v)} label="Tất cả phòng ban" options={initialOptions.departments} /><Select value={filters.location} onChange={(v) => update('location', v)} label="Tất cả địa điểm" options={initialOptions.locations} /><select value={filters.employment_type} onChange={(e) => update('employment_type', e.target.value)} className="rounded-md border border-[#DCCDB9] bg-white px-3 py-3 text-sm"><option value="">Loại hình làm việc</option>{initialOptions.employment_types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select><button onClick={reset} title="Đặt lại" className="grid min-h-11 place-items-center rounded-md border border-[#DCCDB9] bg-white px-4"><RotateCcw className="size-4" /></button></div>
      <div className="mt-6 flex items-center justify-between text-sm text-[#6E6258]"><span>{meta.total} kết quả</span><select value={filters.sort} onChange={(e) => update('sort', e.target.value)} className="rounded-md border border-[#DCCDB9] bg-white px-3 py-2"><option value="newest">Mới nhất</option><option value="deadline">Hạn ứng tuyển gần nhất</option></select></div>
      {loading ? <div className="grid gap-4 py-6 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(i => <div key={i} className="h-64 animate-pulse rounded-md bg-[#F4EEE4]" />)}</div> : jobs.length ? <div className="grid gap-4 py-6 md:grid-cols-2 xl:grid-cols-3">{jobs.map(job => <JobCard key={job.id} job={job} />)}</div> : <div className="my-8 rounded-md border border-dashed border-[#DCCDB9] p-12 text-center text-[#6E6258]">Chưa có vị trí phù hợp với bộ lọc hiện tại.</div>}
      {meta.last_page > 1 && <div className="flex justify-center gap-2">{Array.from({ length: meta.last_page }, (_, i) => i + 1).map(value => <button key={value} onClick={() => setPage(value)} className={`grid size-10 place-items-center rounded-md border ${page === value ? 'border-[#B88746] bg-[#B88746] text-white' : 'border-[#DCCDB9]'}`}>{value}</button>)}</div>}
    </div></section>

    {!!content.process?.length && <section className="mx-auto max-w-[1344px] px-4 py-12 sm:px-8"><h2 className="text-3xl font-semibold">Quy trình tuyển dụng</h2><div className="mt-7 grid gap-px overflow-hidden rounded-md border border-[#E7D9C6] bg-[#E7D9C6] sm:grid-cols-5">{content.process.map((step, index) => <div key={index} className="bg-white p-5"><span className="text-2xl font-semibold text-[#C99A55]">{String(index + 1).padStart(2, '0')}</span><p className="mt-3 font-semibold">{step}</p></div>)}</div></section>}
    {content.allow_general_application && <section className="mx-auto max-w-[1344px] px-4 pb-14 sm:px-8"><div className="flex flex-col items-start justify-between gap-5 rounded-lg bg-[#1F1B16] p-7 text-white sm:flex-row sm:items-center"><div><h2 className="text-2xl font-semibold">{content.cta_title}</h2><p className="mt-2 text-sm text-white/70">{content.cta_description}</p></div><button onClick={() => setApplyOpen(true)} className="rounded-md bg-[#C99A55] px-5 py-3 font-semibold">Gửi hồ sơ tự do</button></div></section>}
  </main><Footer /><CareerApplicationForm open={applyOpen} onClose={() => setApplyOpen(false)} rules={initialOptions.application_rules} /></>;
}

function Stat({ icon: Icon, value, label }: { icon: typeof BriefcaseBusiness; value: number; label: string }) { return <div className="flex min-w-0 items-center justify-center gap-2 border-r border-[#E7D9C6] px-2 py-4 last:border-0 sm:gap-4"><Icon className="hidden size-5 text-[#B88746] sm:block" /><div><strong className="block text-xl text-[#1F1B16]">{value}</strong><span className="text-[11px] text-[#7B6D61] sm:text-sm">{label}</span></div></div>; }
function Select({ value, onChange, label, options }: { value: string; onChange: (v: string) => void; label: string; options: string[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="rounded-md border border-[#DCCDB9] bg-white px-3 py-3 text-sm"><option value="">{label}</option>{options.map(option => <option key={option}>{option}</option>)}</select>; }
function JobCard({ job }: { job: CareerJob }) { return <article className="flex min-h-64 flex-col rounded-md border border-[#E7D9C6] bg-[#FFFCF7] p-5 transition-shadow hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div>{job.is_featured && <span className="mb-2 inline-block rounded-full bg-[#B88746] px-3 py-1 text-[10px] font-bold uppercase text-white">Nổi bật</span>}<h3 className="text-xl font-semibold leading-snug">{job.title}</h3><p className="mt-1 text-sm font-medium text-[#9A682F]">{job.department}</p></div><BriefcaseBusiness className="size-6 shrink-0 text-[#C99A55]" /></div><div className="mt-5 grid gap-2 text-sm text-[#6E6258]"><span className="flex gap-2"><MapPin className="size-4" />{job.location}</span><span className="flex gap-2"><Clock3 className="size-4" />{job.employment_type_label}</span><span className="flex gap-2"><UsersRound className="size-4" />{job.vacancies} vị trí · {salary(job)}</span><span className="flex gap-2"><CalendarDays className="size-4" />Hạn: {date(job.application_deadline)}</span></div><Link href={`/tuyen-dung/${job.slug}`} className="mt-auto flex items-center justify-between border-t border-[#E7D9C6] pt-4 font-semibold text-[#8A5B28]">Xem chi tiết <ArrowRight className="size-4" /></Link></article>; }
